spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:employeeApplication
    username: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: Employee Application

server:
  port: 8080
